### ISSUE TITLE
FluentReportsGenerator: Support integration with WebComponents

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#101]
Our application uses WebComponents extensively. Several places in the new library, `document.getElementById()` is used, but due to the ShadowDOM, the element won't be able to be found. Ideally we could pass an element reference to the FluentReportsGenerator instance that could be used as the root element. It would also make it more efficient since we already have a reference to the element we need, and wouldn't have to query the DOM for it.

**Comment by NathanaelA** [comment]
So I assume you are embedding the fRG into a web component; which is why the fRG can't access the getElementById, correct?      Does any of the getElement's work; even if they are off a parent element in the shadow dom?

Yes, we can change the logic so you can pass an actual element in addition to the class name...

If you don't mind, can you create a sample webcomponent that embeds fRG into it so I can make sure everything works.   I'm sure I could read the docs and figure it out; but if your used to doing it -- I'm sure you would do it much faster creating the skeleton.  :grinning:

**Comment by beaudesigns** [comment]
Sure thing! I modified the original sample you sent us.

I am not set on the naming at all. I don't mind if you want to allow passing an element to `id`, or if you'd prefer a different name for the option when you pass an element reference. The key thing is just being able to pass a reference that gets used, instead of having to query the DOM for a specific ID.

https://gist.github.com/beaudesigns/a71814e0890157a0ade5e661fe4c486b

**Comment by NathanaelA** [comment]
Thanks that got me going.   Sorry for the time it took me a long while to solve all the issues from running inside an actual shadow dom.    Working inside the custom component was easy, but the minute I attached it to the shadow dom, the behavior totally broke...

This is fixed in the next version.
