### ISSUE TITLE
FluentReportsGenerator: Add shape printing

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#106]
We use `.line()`, `.box()`, and I believe in one or two cases, `.circle()`.

We also capture data from Wacom signature pads and use that information to draw signatures. Behind the scenes we're currently using `.line()` with the pressure data controlling the thickness of the line. We wrote a custom implementation to define a box to scale the data to. `renderSignature(report, sigData, left, top, width, height, options)`

**Comment by NathanaelA** [comment]
`.line`, `.box`, and `.circle` I'll try and get into one of the next versions...  Should be easy to add.

---

As for the signature:

One of the built in options is a printFunction; you can then using the printFunction element, call your renderSignature function with the current report, etc...  All function's support async or sync calls, so it is very flexable.

However, another thought -- maybe we could also extend the report generator with the ability to add and register new elements in the report -- so you could create a signatureElement and it would auto be added to the tool bar, be readable and writable to the json file -- with any properties you need exposed.      Don't know how often you need to make the embeddable sigs accessable in the editor; but it is a thought that allows custom elements to be easily added...    

In addition thinking out loud --- the fRG already supports a 'locked' to lock an item from moving; I could easily also add a `readonly` so then you could pre-add the signature code to the master json code/report -- and then set the locked & readonly fields in the json so that the end user can't mess with that specific item...

**Comment by beaudesigns** [comment]
I missed the flexibility of the `printFunction()` type! I'll have to do some testing to make sure it covers what we need. If it does, then I think that covers our need, I don't think we'd need the added complexity of being able to register new elements. Thanks!

**Comment by NathanaelA** [comment]
This has been added to the generator and builder.   You now have access to PrintShape item.
