### ISSUE TITLE
[FRG] - Append dialogs to the parent element

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#109]
There are a few issues with the current dialog implementation. They are they are appended to the `body` element and when `hide()` is called, they are just hidden from display, and never cleared from the DOM. Since there is no `.destroy()` functionality for fRG, those DOM elements hang around on the `body` even if the parent element is removed. Since they're numbered, I think you might end up with conflicts if you tried to have multiple fRG instances on the same page.

If the dialogs were appended to the parent element, I think that would solve a couple of issues. One would be z-indexing, which can just be relative to the parent, another would be destructing.

It also allows the fRG editor to be more self-contained within web components, where the styles can be contained to the Shadow DOM.

**Comment by NathanaelA** [comment]
1. Good catch -- the dialogs are actually reused; but when the frg element is destroyed the dialogs should be destroyed also...   So the destroy code does need to be added.

2. As for conflicts; this should not happen since the dialog actually acts just like a dialog and none of the frg's are active when a dialog is active...  So you can't shouldn't' be able actually create a dialog from more than one frg instance at a time.  :-)

**Comment by beaudesigns** [comment]
Cool!

Yes, on the z-indexing. The report editor is being embedded on a panel element, which can be behind or in front of other panels, and at a dynamic z-index depending on how many panels are open.

That also means that panels do not take up the full size of the screen, so the dialog overlay may cover more than the area of the panel. My opinion for the simplest solution, is to make the dialog contained inside of the editor element (position relative on the editor, position absolute on the dialog). That'd eliminate any overflowing and z-indexing issues almost completely. But you may have a better idea!

**Comment by NathanaelA** [comment]
I will try and add a option to append this to the parent element in one of the following versions.
This will take a little bit of time to pass the root element; since the whole dialog system just assumes it is going off the very root document element.    So I basically have to pass the root frame from the editor to the UI system which will then pass it to the dialog system...

**Comment by beaudesigns** [comment]
That's fair, I may see if I can come up with a styling workaround for now so that dialogs aren't behind the panels.

**Comment by NathanaelA** [comment]
This is fixed in the next version.
