### ISSUE TITLE
[FRG] - Add a way to manage sub/sibling-reports

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#121]
I don't see a way to manage or manipulate subReports in the editor, when I manually add a subReport to the Structure, I can see that there is one in the report "Sections" view, but I don't see a way to manage that subReport, or mark it as a sibling, etc.

**Comment by NathanaelA** [comment]
Their is no siblings sub-reports yet in the editor; basically the any child datasets create automatic subreport.   Clicking on the body of the detail of the child dataset is the subreport.      Is their some specific thing you need.

**Comment by beaudesigns** [comment]
Cool! So it's driven off the data. I think that basically works. I honestly haven't used sibling reports personally, but do we need a way to mark it as a sibling instead of a sub-report?

The example would be a some detail gets printed out, and then there's a 2nd page with related data, but not any kind of sum or aggregate data. Just a related dataset that's it's own "report".

**Comment by NathanaelA** [comment]
Fixed in latest release.
