### ISSUE TITLE
[FRG] - Add a way to access data in titleHeader

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#122]
We have found that we need to be able to access data in the `titleHeader`. Probably keeping it consistent with `header()` and `footer()`, where it provides the first row is enough for now, but I could also see a case for just passing the entire dataset. I'll leave that up to you. My personal preference would probably be just the first row of the dataset.

That way a "Print function" in a title header can access data for header information, like "Time Sheet for: NAME".

I know in some cases, header and footer can be used, but if the report spans more than 1 page, it really needs to be a titleHeader.

**Comment by NathanaelA** [comment]
This would require a bit of reworking of the actual base engine; FR at the point it actually prints the `titleHeader` hasn't event requested any data.    So it is completely unaware of data, which is why the data is null at that point.     

I can add it to my list if this is something you will need.   Any specific priority?

**Comment by beaudesigns** [comment]
Is there any alternative way that you can think of to handle this scenario with the new FluentReportBuilder? Previously, since we were defining a `titleHeader()` function inline, we could just reference the data variable outside of the scope of the header function.

Now that the reports are more self-contained, we don't have the ability to just assign a variable and use it inside of a report `titleHeader()` function.

I'm very open to suggestions on how this should be accomplished.

**Comment by NathanaelA** [comment]
Ok, I have coded up a bit of a hack, which should work in most cases.   As long as the data is passed into the builder/runner, the first record will be passed to the title header function now.

---

If you are using a dataset that is pageable; then it will act as it now does where the record is null, since it hasn't actually gathered any data yet.    To support pagable data; would require a bit of changes to the engine.

**Comment by ymendelsohnYoobic** [comment]
I still didn't understand how it should work. Currently I'm doing this:
`rpt.header(function(report, data) {
    report.print(data.title, { fontSize: 22, bold: true, underline: false, align: 'left' });
})`
but `data` is null.
I previously called `Report.data({title: 'Hello World'})` so as I understand it should be there.

Thanks in advance!

**Comment by NathanaelA** [comment]
@ymendelsohnYoobic - The above issue was for a related issue in the Report Builder/Runner system.  In the normal report system, the actual PAGE header function won't have access to the raw data as it hasn't actually gathered any data.   There is two ways to deal with this:
1. You can access the original data item.  
```
const myData = {title: 'Hello World'};
rpt.data(myData);
rpt.header( (report, data) => { report.print (myData.title, ...); });
```
Because myData is in the parent, scope you can access it in any child functions.
Or you can use userdata to pass around an object that you want to be able to access in a function.
```
rpt.userData(myData);
rpt.header(report, data) => { report.print(report.userData().title, ...); });
````

**Comment by ymendelsohnYoobic** [comment]
Got it, thank you!
