### ISSUE TITLE
[FRG] Formatter functions do not support `return`

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#163]
This may be intentional, but it doesn't seem to fit the pattern of other places in the system.

Currently, it seems like formatter functions in bands require that you use the `callback()` to return the value.

**Works**
```
structure.formatterFunctions['percent'] = "callback(`${value}%`);";
```

**Does Not Work**
```
structure.formatterFunctions['percent'] = "return `${value}%`;";
```

**Comment by NathanaelA** [comment]
This is intentional, the report engine has a lot of "extra" code now because of sync vs async and trying to do the right thing.    In some cases this has creates some major complexity and we don't want any extra complexity in the massive number of loops band calls handle, if we can avoid it...

I would like to over time simplify the engine to be always fully async and eliminate all the sync paths, which should make things be a lot more standard.     Which basically means anything that calls into user code must be callback based to allow the user to do their own async path before running the callback with the result.   In fact if I get the opportunity to rewrite it; I'd be using things like promises, async/await, and generators to simplify the code base greatly.  :-)

---

Unless there is a really compelling reason to add sync support here, I would rather not.  :grinning:

**Comment by beauwest** [comment]
Love it! I actually like the consistency. I can work with callbacks until
we get promises. Thanks!
