### ISSUE TITLE
Export to Download PDF not save locally

### ISSUE THREAD

**Issue by jfreak53** [NathanaelA/fluentreports#19]
I'm not finding this in the documentation. I want to serve this in a web application, not CLI. How do I get the Report Framework to "not" save the PDF locally to the server but send it to the browser in PDF to download for the person viewing the page?

**Comment by Nathanaela** [comment]
There is a couple ways:

1. You can write it to disk; so that whatever http(s) server you are using can then stream it as a normal file with the pdf mime type.    Then after sending the file you can either delete or keep the file.   Depending on which http(s) server you are using this can be very easy to do.  

2. You can also write the pdf to a stream, then stream the stream to the client using either http or sockets.   But if the reports are REALLY large; you run the risk of using all your memory on the server while it is generating it and storing it in the stream before it streams it (since everything stays in memory)

3. I haven't tested it; but theoretically the code was written such that you should be able to build the pdf completely on the client side in their browser as long as you stream the data needed to make the report over to the client from the server.    One of these days, I'm going to double check this works -- but I don't see any reason why it won't unless I have a bug somewhere...

I am personally using the first option in a project, as it not only allows the server/client to negotiate the optimal method to transmit the file.   But it totally eliminates the possibility of running out of memory when generating very large reports for several people at the same time.

**Comment by Nathanaela** [comment]
I should mention; their are two ways of streaming it.   
1st, if you pass a string with the value of "buffer" (instead of a filename) as the first parameter of the 
```js
var rpt = new Report("buffer", options);    
rpt.render(function(err, data) {
  // data will be the entire pdf in a buffer
});
```

The second way is if you pass a stream in:
i.e.
```js
var ws = new WritableStream();  // Whatever writable stream object you want
var rpt = new Report(ws, options);
rpt.render(function(err) {
  // The pipe should have been fully filled and the pdf was fully pipped to this stream by this point
});
```

**Comment by leoncc** [comment]
Hi,

I'm using the MEAN stack (obviously with AngularJS, Node and MongoDB):

In client controller inject $window at the top where you declare the controller. Then the function below is called for instance from a view with ng-click on a hyperlink or image):

```javascript
		$scope.generatePDF = function() {
			$http.get('daily-orders-report',{headers: {}, responseType: 'arraybuffer'})
				.success(function (data) {
					var file = new Blob([data], {type: 'application/pdf'});
					var fileURL = URL.createObjectURL(file);
					$window.open(fileURL);
				}
			);
		};
```
Server side in controller - note that res the response is actually a writable stream, so you don't have to work very hard by creating a writeable stream on the server. So your route on your server side would call generatePDF: 

```javascript
exports.generatePDF = function(req, res) { .........
...............
		var rpt = new Report(res)
			.autoPrint(false) // Optional
			.pageHeader( ['Employee Hours'] )// Optional
			.finalSummary( ['Total Hours:', 'hours', 3] )// Optional
			.userdata( {hi: 1} )// Optional
			.data( mydata )	// REQUIRED
			.sum( 'hours' )	// Optional
			.detail( daydetail ) // Optional
			.totalFormatter( totalFormatter ) // Optional
			.fontSize(8); // Optional
```

Hope it helps 
Leon
