### ISSUE TITLE
Question about how page breaks work with groups

### ISSUE THREAD

**Issue by dlong500** [NathanaelA/fluentreports#21]
I haven't had a lot of time yet to play around with fluentreports, but before I spend a lot of time trying to migrate from other solutions, can you explain how the engine handles page breaks for groups of data?  Are there options to have the engine dynamically insert page breaks to keep groups from spanning pages?  In other words, if I have 9 rendered groups in a report and it can only fit 2 on the first page, 3 on the second, 4 on the third can it automatically do this?  Having the ability to prevent a group from spanning pages (assuming a rendered group will fit on a single page) is a necessary feature for my needs.

Also, what is the status of the pre-rendering system you mentioned that would give the ability to have context for things like total number of pages?

**Comment by Nathanaela** [comment]
If I understand your question correctly, then the answer is yes.     If you are printing a Grid; then it will break the grid before; and reprint headers and everything for you and your items will fall the way you are discussing.          

If you are printing free flow text; then it will print as much of the text; then break it.    However, since you are totally in charge of each part  of the report at the point you are generating the report you can very easily first ask the engine how much space this "data" you are going to output takes (just before outputing it); and then call newPage() if it is too big.     Does that make sense?

As for the pre-rendering; it hasn't even been touched.   It is a feature idea; and their haven't been any +1 to it; so it isn't a high priority.   And yes, it would allow the engine to know the total number of pages.      

    But if you *really* want to know the total number of pages; you can actually render the report twice and save the page number of the final summary; then use that number in the second generation of the report.  ;-)
