### ISSUE TITLE
newPage() doesn't cause header to be rendered on the new page

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#254]
Example code:
```
const {Report} = require('fluentreports');

new Report('test.pdf')
  .data({})
  .groupBy()
  .header(r => r.print('HEADER'))
  .detail(r => {
    r.print('PAGE1');
    r.newPage();
    r.print('PAGE2');
  })
  .render(err => {
    if (err) throw err;
  });
```
Page 2 just says "PAGE2", not "HEADER" also as expected. Is this the intended behavior for `newPage()` and if so, why?

**Comment by NathanaelA** [comment]
If you want it to actually do a full page break, you need to pass in:
`r.newPage({breakingBeforePrint: true});`
or you can use `pageHeader()` instead of `header()` which is then printed on all pages.   Because you used `.header` after the .groupBy() the .header is for that group and as such headers it is printed only at the beginning of the group if I recall correctly.

**Comment by gillsonkell** [comment]
Didn't know about `breakingBeforePrint`, thanks, that did the trick!
