### ISSUE TITLE
How to implement Typescript support?

### ISSUE THREAD

**Issue by DiegoVega19** [NathanaelA/fluentreports#270]
I wanted to know how can I implement Typescript?
Regards
Awesome package!

**Comment by NathanaelA** [comment]
Not quite sure the question you are asking...

1. If you are wanting to use this in TypeScript, any JS code works as-is, you just don't get as good of auto-detection of issues/and knowledge of the types.    So when you do `let rpt = new Report` it doesn't know rpt is actually a Report group object...

2. If you are asking how to actually create a Typings file for FluentReports [would love someone to do so, or pay me to do so], then you have to create a `.d.ts` file with the class types so that your editor.   You might even be able to start with the JSDoc info and have it parsed into a `.d.ts` file.
