### ISSUE TITLE
GroupBy creates to much groups

### ISSUE THREAD

**Issue by bgaertne** [NathanaelA/fluentreports#272]
If i generate a band on this data:
const data = [
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"John", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"Doe", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"Doe", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"Doe", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"Doe", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"Doe", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"Doe", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
            { Anbieter:"John", Kategorie:"A",Punkte:3},
            { Anbieter:"John", Kategorie:"A",Punkte:5},
            { Anbieter:"Doe", Kategorie:"B",Punkte:6},
            { Anbieter:"Doe", Kategorie:"B",Punkte:2},
            { Anbieter:"Klaus", Kategorie:"B",Punkte:9},
        ];

it will create 24 groups if you group by Anbieter, because it groups datasets only if there is no item with another Anbieter-property  between them, so i have to sort the datasets before it can be grouped. Is this the desired behaviour?

Thank you in advance

**Comment by NathanaelA** [comment]
Yes, the report system doesn't sort anything because it doesn't actually know how you want the data sorted -- it assumes you sorted it first so that the data is output in the order you want it....   You might have some other key that is important to split things on that you don't tell the report system because there is no reason to list it.   

So if you have unsorted data, just use something like this:
```
data.sort((a,b) => { 
  if (a.Anbieter === b.Anbieter) return 0;
  if (a.Anbieter < b.Anbieter) return -1;
  return 1;
});
```
Assuming the `Anbieter`  is your criteria, but you can sort on as many pieces of data  as you want inside that function as basically records before should be a -1, records equal is 0 and records moved after are 1...

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
