### ISSUE TITLE
Question: What is the reason for the error regarding "footer prints some text then makes an absolute move greater than 1/3 of a page"?

### ISSUE THREAD

**Issue by DarkGuardAce** [NathanaelA/fluentreports#70]
This error seems to be intentional, but we have a few use cases where we intentionally go down this path and don't want to get the error - especially since we use a custom handler that `throw`s when an error is encountered.  An example of the sort of thing that we try to do can be seen here, along with a hacky workaround: https://npm.runkit.com/fluentreports

```
var fluentreports = require("fluentreports")
var Report = fluentreports.Report
var header = function (rpt, data) {
  rpt.newLine();
  rpt.print(data.comments);
};

var footer = function (rpt) {
  rpt.newLine(4);
      
  //// workaround code - add to "fix"
  /*rpt.print(' ', {y: 100});
  rpt.print(' ', {y: 200});
  rpt.print(' ', {y: 300});
  rpt.print(' ', {y: 400});
  rpt.print(' ', {y: 500});
  rpt.print(' ', {y: 600});
  rpt.print(' ', {y: 700});*/
  ////
      
  rpt.print('testing footer data', {fontBold: true, fontSize: 8, y: 740});
};

var rpt = new Report();


rpt
  .margins(30)
  .header(header)
  .footer(footer)
  .data([{comments: 'test'}]);

rpt.render();
```

Note the `newLine()` into `print(..., {y:>1/3 the page})`.  I'm looking for a way to resolve this but am missing the context as to why the code catches this particular scenario.  My initial thinking is that the check is not needed, since a user can legitimately print some text then move greater than 1/3 of a page and continue printing, however I'm sure that there is more to it than I am seeing.   :)    My second theory is that it might should check for "overflows off the end of the page" rather than "moved greater than 1/3 a page".  I would appreciate any clues you can give as you have time.  Thanks!

**Comment by NathanaelA** [comment]
The reason for that **warning** is because it is detecting what could be an nasty error in your report footer.    This situation is only detected and notified during the initialize sizing of components and it only applies to the footer sections.

So lets take a sample report  (# pound number is Y location in this example:)

```
[header]  (# 50)
[text] (# 100)
[text] (# 150)
[text] (# 200)
[footer text] (# 250)
-> Move to Y - 550   (# 550)    
[more footer text] (# 600)
```

Calculation is now that the footer is 400 pixels high.  That probably isn't what you actually meant; you probably wanted: 

```
move to location;  (450)
[Footer Text] (500)
Move to new Location (550)
[More footer text] (600)
```


so that the measurement of the footer is actually only 150 pixels starting at the 450 mark...

Odds are very likely this is a bug in your report; but it will still let you print it.  Again this is just a warning; it doesn't actually stop the printing, but you have very good odds the report isn't going to present the way you expected it too when it detects this issue...   

---

Modifying your code:

```
var footer = function (rpt) {
  // rpt.newLine(4);   //  <-- Why do this?  You just hard moved to 740 in the next line; this is pointless statement (causes the warning to occur) and can be removed...
  rpt.print('testing footer data', {fontBold: true, fontSize: 8, y: 740});
};
```

If you eliminate the redundant `newLine(4);` then you won't get that warning anymore; because your very FIRST print statement moved the starting point for Y to 740.   :grinning:

**Comment by DarkGuardAce** [comment]
That makes sense.  So the 2 corrections in my understanding are:

(1) Report.error() isn't specifically for "error" level output - warning come through here too.  So my `throw`ing all messages as errors won't necessarily work as intended.  This message _does_ make sense as a warning, since it is simply a heads up that something may not be working as intended.

(2) My specific case does have those 4 newLines(), but it doesn't need them - it is leftover from an old iteration of the report, I'm sure.  In these scenarios I can either handle the warning that is correctly generated from the strange approach or fix the report code itself (which sounds like the best option in my case).  Neither of these are issues in fluentreports, but rather are changes we would need to make on our side.

Thank you for the explanation, sir!   😄

**Comment by NathanaelA** [comment]
(1) - Yes, another option is that we could create a "Report.warning" call, or the new ReportError class could have a warning flag set on it.

**Comment by DarkGuardAce** [comment]
Yes, either of those approaches make sense to me.  Your explanation cleared up my misunderstanding, but making one of those changes could have value still.  Along with that, would it make sense to have errors `throw` while warnings simply give a message?  Your ability to easily add custom error handlers allows the developer to do this themselves, but I could see it being useful in the base code too - so long as there isn't a drawback to doing so that I am not considering.
