### ISSUE TITLE
Wrong text position when Rpt.print page break

### ISSUE THREAD

**Issue by xypherbo** [NathanaelA/fluentreports#73]
I have Rpt.print at near the bottom of the page that has the footer and it was the long text that will auto page break. But when page break happens the text position was inside the header region

**Comment by xypherbo** [comment]
You can see it appearance at this link https://drive.google.com/file/d/1ab1mLjNa1ensu-7LQoJficfTNc87d1zd/view?usp=sharing

**Comment by xypherbo** [comment]
I have found some hacky fix that moves text in the right position.
just setCurrentY at the end on header render and it fixed but it should be done automatically

**Comment by NathanaelA** [comment]
I would have to see the code that generates the report to be able to see what is wrong...

**Comment by asvilela** [comment]
I'm with same problem.
The "finalSummary" invades the footer area.
[RHJC72H2SHU_23062018_094810.pdf](https://github.com/NathanaelA/fluentreports/files/2129906/RHJC72H2SHU_23062018_094810.pdf)

**Comment by NathanaelA** [comment]
Without some source to show the issue; I can't really diagnose why it occurred.

**Comment by asvilela** [comment]
I'm sending my code...
[pdf-quote-service.js.tar.gz](https://github.com/NathanaelA/fluentreports/files/2146622/pdf-quote-service.js.tar.gz)

**Comment by asvilela** [comment]
Does NathanaelA have any news?
I already sent my code.

**Comment by NathanaelA** [comment]
@asvilela  - I have not had a chance to look into it in depth; I have downloaded everything and briefly looked at it and didn't see anything obviously wrong.    I have to have some spare time to create a dummy data set that can render your report with your code. 

As much as I would love to fix it asap; at this point, since I do contract development those that are paying me for work get priority over open source stuff.  ;-)

**Comment by asvilela** [comment]
I am forwarding the dummy data to facilitate the analysis.
[dummyData.txt.zip](https://github.com/NathanaelA/fluentreports/files/2207135/dummyData.txt.zip)
;)

**Comment by NathanaelA** [comment]
@asvilela - Is this what you are expecting?

![image](https://user-images.githubusercontent.com/850871/42912255-113e6022-8ab4-11e8-8919-af76d03100f2.png)

Since the Final Summary is larger than the space left; it is now paged in its entirety to the next page (and the current pageFooter is used for the current page).   That has been the original design. but it wasn't being measured so the engine was treating the pageSummary as a 0 sized element.   So of course it fit, and caused the issue in the footer you saw...

**Comment by NathanaelA** [comment]
@xypherbo - Any chance you can provide me a sample report that shows broken behavior?
