### ISSUE TITLE
Unexpected setCurrentX behaviour

### ISSUE THREAD

**Issue by InfinitySamurai** [NathanaelA/fluentreports#82]
`setCurrentX()` does not behave as I expected when using `report.print()`. Instead of setting the x position for the next print, it is still aligned to the left of the page.

```js
    rpt.setCurrentX(300)
    // does not print at x: 300
    rpt.print("test1")
    // prints where expected at x: 300
    rpt.print("test2", {x: 300})
```

I'm unsure whether this is by design, but it was not what I initially thought would happen when trying to create 2 columns of information in my header.

**Comment by NathanaelA** [comment]
You are correct; this setCurrentX is being overridden as the print function starts.   I'll have to look into why this change was put into place and see if we have to leave it or if we can remove it safely.  :grinning:

**Comment by Aletta93** [comment]
This unexpected behavious doesn't only happen with print, but in general. The only way for me to display data dynamicaly over the x-axis of the report is to use the above "solution". Using `setCurrentX([new coordinate])`, `addX([amount])`, or `currentX([new coordinate])` does not work at all for the display of data. It does however work for drawing a box.

**Comment by NathanaelA** [comment]
We might need to add a flag to respect the last currentX location to the print routine. Would that be an acceptable solution?

**Comment by NathanaelA** [comment]
Unfortunately `print` and `band` are special cases where they need to typically start at the left most margin for consistency, since they will follow other commands frequently; we want the 
```
.print("1")
.print("2")
```
to be laid out properly on two lines at the left most column without any other changes.... 

So to handle you leaving print where it is at `print` now has a new option: `useCurrentX: true` to use the existing current X value; so you can pass that in now instead of using the {x: 300}...
